print("Baivab Sarkarr")
print("Kazidanaga,Bandel")
print("P.O Debanandapur,P.S Chinsura")
print("Hooghly,West Bengal,712123,India")
print("Telephone: 8961428548")
print("E-Mail: baivabsarkar@gmail.com")